# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rubyx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rubyx)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,61632c848a29af5604a4547d17c668dbe2a6e54c)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,bd8c1c1dc26a78fae5c363ed46272be39e115b90)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,7acc810edd7f32f2cb0726beb04a002cf1a4e3b3)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,9dbec1f8ad28ac15af3506633d9f2de2438ce143)
$(call add-radio-file-sha1-checked,radio/dpm.img,97e645d06896a877774ee21d3b97f09dffaf053a)
$(call add-radio-file-sha1-checked,radio/gz.img,5fe87d8cea0cf9c6a98f4b0e5c593fbe218321d5)
$(call add-radio-file-sha1-checked,radio/lk.img,fc1b202d35e61c2f4f805d9683833fa33894ce58)
$(call add-radio-file-sha1-checked,radio/logo.img,d2ad8097ee6339be5d35c0da7832995b7c253c77)
$(call add-radio-file-sha1-checked,radio/mcupm.img,0b24a477a8969cc1ded964003fc20e9998d1acce)
$(call add-radio-file-sha1-checked,radio/md1img.img,4f0bad1c057a404376344a2ef2e1a100f67ebd48)
$(call add-radio-file-sha1-checked,radio/pi_img.img,f4d653b41f92c6048ebe67c0e30813af28fa7a55)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,f96daaceea3f67adee52d79cddef188dbb480ff8)
$(call add-radio-file-sha1-checked,radio/scp.img,f33a0ec1cbb4efb8d39067427fbe07591a182f39)
$(call add-radio-file-sha1-checked,radio/spmfw.img,a5a893345b1bfedc5788790b6e53de8a968241ba)
$(call add-radio-file-sha1-checked,radio/sspm.img,9cd6ebda8ed203e05454f92fde230c631e9946a5)
$(call add-radio-file-sha1-checked,radio/tee.img,756b7a4834d0ba75f557badfbfc4d05f039ddb1d)

endif
